import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '@/features/header';
import { Providers } from '@/context/jobs-query-provider';
import { TanStackProvider } from '@/providers/TanstackProvider';
import {
  getSession,
  getUserOrganization,
} from '@/features/auth/services/auth.services';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [session, sessionError] = await getSession();
  const [userOrg, userOrgErr] = await getUserOrganization();

  if (sessionError || userOrgErr) {
    console.error(sessionError);
  }

  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanStackProvider>
          <Providers>
            <div className='min-h-screen bg-background'>
              <Header sessionData={session} userOrg={userOrg} />
              <div className='max-w-7xl mx-auto px-4 min-h-screen'>
                {children}
              </div>
            </div>
          </Providers>
        </TanStackProvider>
      </body>
    </html>
  );
}
