import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '@/features/header';
import { Providers } from '@/context/jobs-query-provider';
import TanStackProvider from '@/lib/providers/tanstack.provider';
import { getSession, hasOrganization } from '@/features/auth/lib/auth-helper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [session, sessionError] = await getSession();
  const [hasOrg, orgErr] = await hasOrganization();

  if (sessionError || orgErr || !session) {
    console.error(sessionError);
    return null;
  }

  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanStackProvider>
          <Providers>
            <Header sessionData={session} hasOrg={hasOrg} />
            {children}
          </Providers>
        </TanStackProvider>
      </body>
    </html>
  );
}
